### ISSUE TITLE
Task 1.4.1 - AIDE rename

### ISSUE THREAD

**Issue by Craconia** [jbertozzi/ansible-role-cis-rhel8#6]
If we're doing the whole thing with AIDE; setting a cron job etc...it won't work as there's no /var/lib/aide/aide.db.gz (a rename from the NEW to default nees to take place).

I changed the init task from:

command: /sbin/aide --init

to

shell: /sbin/aide --init && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz

and changed args accordingly:

#creates: /var/lib/aide/aide.db.new.gz
  creates: /var/lib/aide/aide.db.gz

Using shell with && may not be elegant but it does the job...

**Comment by jbertozzi** [comment]
The following commit should fix it: 26efdab.

**Comment by Craconia** [comment]
Hi.  An extra "&&" was inserted during the correction and now the task fails.

Currently:

shell: /sbin/aide --init && && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz


Correct:

shell: /sbin/aide --init && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
