### ISSUE TITLE
Task 4.2.1.5 - @ Sign

### ISSUE THREAD

**Issue by Craconia** [jbertozzi/ansible-role-cis-rhel8#8]
Changed:

line: '*.* {{ cis_rhel8_rsyslog_server }}'
to
line: '*.* @@{{ cis_rhel8_rsyslog_server }}'

...to use TCP transmission.  It could be a single @ for UDP as well. Regardless, you need @ or @@.

**Comment by jbertozzi** [comment]
The commit should fix it: e9bb6ec.
