### ISSUE TITLE
Task 1.5.2 - Task Fails as is

### ISSUE THREAD

**Issue by Craconia** [jbertozzi/ansible-role-cis-rhel8#9]
Had to change  "hast of your password" for "hash of your password is " to make it work, at least in fresh installation of RHEL 8.3 BETA.

Current:

  shell: >
    set -o pipefail ;
    echo -e "{{ cis_rhel8_grub_password }}\n{{ cis_rhel8_grub_password }}\n" |
    grub2-mkpasswd-pbkdf2 | sed -e '/PBKDF2 hash/!d' -e 's/PBKDF2 hash of your password//'

Fixed:

  shell: >
    set -o pipefail ;
    echo -e "{{ cis_rhel8_grub_password }}\n{{ cis_rhel8_grub_password }}\n" |
    grub2-mkpasswd-pbkdf2 | sed -e '/PBKDF2 hash/!d' -e 's/PBKDF2 hash of your password is //'

**Comment by jbertozzi** [comment]
The following commit should fix it: afd676f.
